# Whether to save and backup worlds before resetting.
# When disabled, worlds will be permanently deleted upon reset (much faster).
backup: false

# Whether resets should happen automatically upon the death of all players.
# When disabled, you may instead run `/nonsensehardcore reset` to manually reset the world.
auto-reset: true

# Whether to trigger a reset upon *any* death.
# When disabled, automatic resets will trigger only when all players are dead.
# This setting is ignored if `auto-reset` is disabled.
any-death: true

# How many lives a player should have before they are considered dead.
lives: 1

# How many random datapacks to download each time the world resets.
datapack-count: 10

# In addition to the above datapacks, have a random chance to also add each of these.
# name should be the Modrinth ID or slug (name in project page url) for the datapack.
# chance is between 0 and 1.
added-datapacks: [ 
  { name: "terralith", chance: 0.5 }, # for example, there will be a 50% chance to add Terralith
  { name: "incendium", chance: 0.5 },
  { name: "nullscape", chance: 0.5 },
  { name: "randomizer-complete-edition", chance: 0.15 },
]

# Whether to restart the server automatically.
# If false, the server runs /stop. If true, the server runs /restart.
# Setting this to true is recommended unless you use an environment that auto-restarts
# the server, such as a docker container.
auto-restart: true