name: Fahare
description: Automatically resets your hardcore world when all online players die
version: '${version}'
main: dev.qixils.fahare.Fahare
api-version: '1.19'
authors:
  - qixils
website: https://github.com/qixils/Fahare
