name: NonsenseHardcore
description: Hardcore Mode but it downloads random datapacks from Modrinth
version: '${version}'
main: dev.muno.nonsensehardcore.NonsenseHardcore
api-version: '1.21.7'
authors:
  - muno
website: https://github.com/muno777/nonsense-hardcore
